### ISSUE TITLE
Focus of Draft.js within Shadow DOM

### ISSUE THREAD

**Issue by michaelcox** [Wildhoney/ReactShadow#31]
I'm mounting Facebook's Draft Editor within a `ShadowDOM`. For the most part this works fine except when I try to do a `focus()`.

I've trimmed the problem down in CodePen to illustrate the issue:
https://codepen.io/michael_cox/pen/OmBPBm

When you click on the `Focus` button, it throws the error `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'`. From tracing through the code it looks like it is a valid element, but I might be misunderstanding things. Admittedly this could be an issue with Draft making certain assumptions about the environment that it's running in, but I'm hoping for a simpler solution I might be missing on the `ShadowDOM` side?

**Comment by Wildhoney** [comment]
By stepping through the stack trace I can see that it's traversing up the DOM until it finds `x.ownerDocument.body` which it will never be able to do being under a shadow boundary.

![Screenshot #1](http://i.imgur.com/wBvfzQ9.png)

You can see above what it's _trying_ to do &mdash; Draft is essentially traversing upwards to find the first element is encounters that has an `overflow` of either `auto` or `scroll`:

![Screenshot #2](http://i.imgur.com/Kiz7Qmt.png)

You can *fix* with unknown consequences by applying the requested `overflow` on an element **inside** the shadow boundary, so it doesn't need to keep traversing until it finds the `x.ownerDocument.body` element:

```html
<div style={{ overflow: 'scroll' }}>
```

See line #18 in the [updated JSFiddle](https://codepen.io/anon/pen/oWaLGd?editors=1010) and notice how the focus now works without throwing errors.

Nevertheless, when you type in the `div` it throws more errors, and by stepping through the stack trace of that error you can see it's caused by the `findAncestorOffsetKey` method:

![Screenshot #3](http://i.imgur.com/wFrWHvs.png)

You can see that the method is expecting to stop traversing once it finds the `doument.documentElement` node, which again because you've nested it under a shadow boundary, it will never be able to do.

Conclusion? You could either attempt to find workarounds, but I think the problem essentially lies in the way Draft is written. It's simply making too many assumptions that it's **always** able to access either `document.documentElement` or `x.ownerDocument.body` which because of the nature of shadow boundaries, that just isn't true.

**Comment by michaelcox** [comment]
Thanks a lot for the super detailed response @Wildhoney. I'm going to close out this ticket as there's obviously nothing that can be done in this library. But I'm going to use what you've taught me here to try to come up with a workaround myself. Or (ugh) see if I can get some changes into Draft to support this use case better.
