### ISSUE TITLE
ReactShadow: Files with extension of "less" are unsupported.

### ISSUE THREAD

**Issue by NarasimhaReddyY** [Wildhoney/ReactShadow#33]
Am trying to insert a .less file into a div, but shadow dom throwing a error as .less unsupported.

**Comment by Wildhoney** [comment]
Yep, LESS or SASS are not supported, because it doesn't really makes sense to compile to CSS on-the-fly. Rather you should be doing that in your build process, and then linking to a CSS file from the shadow boundary.

I considered adding on-the-fly LESS/SASS compilation for development only. However I ruled it out because then we'd need a list of loaders as Webpack does.

**Comment by Wildhoney** [comment]
Yep, LESS or SASS are not supported, because it doesn't really makes sense to compile to CSS on-the-fly. Rather you should be doing that in your build process, and then linking to a CSS file from the shadow boundary.

I considered adding on-the-fly LESS/SASS compilation for development only. However I ruled it out because then we'd need a list of loaders as Webpack does.
