### ISSUE TITLE
Why to use this library instead of styled-components?

### ISSUE THREAD

**Issue by metamaker** [Wildhoney/ReactShadow#39]
I am trying to figure out what library works best for me. Both ReactShadow and styled-components are solving same problem though with a bit different approach (using shadow DOM vs generating obfuscated classes). Is there any advantage in using ReactShadow instead of styled-components?

**Comment by Wildhoney** [comment]
I think it's more down to personal preference @metamaker &mdash; as you say, both are solving the same issue. However `styled-components` etc... are more of a temporary solution &mdash; they fix the symptoms and not the cause. With the Shadow DOM standard it's about sitting down and finding a solution based on standards, which I believe in the long-run will always triumph.

Nevertheless, at work I would choose `styled-components` over Shadow DOM for the moment, because of the lack of support in older IE browsers &mdash; even with the polyfill, things can still be unpredictable.

**Comment by metamaker** [comment]
@Wildhoney Thank you for the answer! :beer:
