### ISSUE TITLE
Typescript error on className property

### ISSUE THREAD

**Issue by heyitaki** [Wildhoney/ReactShadow#89]
Hey!

I'm seeing an error on the className property on the root.div element: `Type '{ children: Element; className: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode; }'.
  Property 'className' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'.ts(2322)`

```tsx
import React from 'react';
import root from 'react-shadow';

export default function Test() {
  return (
    <root.div className="root">
      <div></div>
    </root.div>
  );
}
```

I've taken a look at other issues in this repo as well as other resources on this error and am not able to track down the cause... Any guidance here would be greatly appreciated.

**Comment by Kamilczak020** [comment]
@heyitaki as a potential workaround until this is fixed, you could, for example, cast it:

```ts
const ShadowRootHost = root.div as React.FC<React.HTMLProps<HTMLDivElement>>;
```

**Comment by Wildhoney** [comment]
Please try with `18.4.2` guys 👍

**Comment by brentvollebregt** [comment]
A couple of years late for the above, but I figured out the issue above.

**Issue**

`JSX element type 'root.div' does not have any construct or call signatures. ts(2604)` is shown when I do this,

```tsx
import root from "react-shadow";

const Example = () => <root.div>Test</root.div>
```

**Why this happens**

My tsconfig.js sets the `noUncheckedIndexedAccess` compiler option to `true` ([docs](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess)).

The type of the default export (`root` in this example) is,

```ts
type Root = {
    [name: string]: React.ComponentType<
        React.HTMLProps<HTMLElement> & IProps
    >;
};
```

Since we are trying to access a key on the `Root` type, `noUncheckedIndexedAccess=true` correctly protects us from accessing something that might not be in the object (`root`) represented by the `Root` type.

**The fix in usages**

Tell TypeScript it will be there using `!` or throw an error if it is undefined - then use the component.

```tsx
import root from "react-shadow";

const Example = () => {
  const ShadowDomDiv = root.div!;
  return <ShadowDomDiv >Test</ShadowDomDiv >
}
```

**The fix for the library**

The fix for everyone would be to specify exactly what fields are available on this `Root` type.

> May be easier said than done

**Comment by Wildhoney** [comment]
There is [a TS rewrite](https://github.com/Wildhoney/ReactShadow/tree/react-18/src) that I started but haven't yet finished, if anybody wants to help out  😀 iirc it's _almost_ there
