### ISSUE TITLE
Element is duplicated inside <script>

### ISSUE THREAD

**Issue by esprehn** [Wildhoney/ReactShadow#9]
It's not clear why the element is duplicated inside a script tag, or why the content is wrapped inside a ```<main>```. This means React is updating twice as many DOM nodes though, and putting yourself as a child of script just makes you display: none, it doesn't do anything else.

**Comment by tjwudi** [comment]
I think this is solved in #8

**Comment by Wildhoney** [comment]
It's duplicated because of [event retargeting](https://github.com/Wildhoney/ReactShadow#event-retargeting) &ndash; `ReactShadow` finds the related DOM element and emits the event from that element. Also React.js has issues with the DOM structure purely inside of the shadow root.

It's in a `script` tag purely for presentation. It would operate in exactly the same way without the `script` element. It could just as well be a `section` element with `display: none;`.

**Comment by mcxii** [comment]
This method has an unfortunate drawback of leaking possible inline styles in DOM (for instance when displaying external HTML snippet using shadow DOM instead of an `iframe`). Adding something such as this before the original DOM gets wrapped in `script` on `componentDidMount` helps to remedy the issue:

```javascript
var s = this.getDOMNode().querySelectorAll("style");
var i = s.length;
while (i--) { s[i].remove(); }
```

Maybe there's a better way?

**Comment by Wildhoney** [comment]
Elements will no longer be duplicated with https://github.com/Wildhoney/ReactShadow/tree/react-15.0
